### PR TITLE
Changed Design

### PR DESCRIPTION
**Pull request by marceloneil**
Used Bootstrap to achieve a more bearable design, while still continuing
the application's minimalist feel.

I am not sure the functionality is consistent with the previous version, but any errors can surely be resolved with ease

### CODE REVIEW

**Comment by pstakoun** [comment]
Breaks functionality substantially. Transition to bootstrap must be more gradual.

**Comment by marceloneil** [comment]
In what way?
I may be able to try to fix it.

**Comment by pstakoun** [comment]
The application relies on a css data tag to change display names, but I think we can make it work.

**Comment by marceloneil** [comment]
I though I kept those in...

I took out the style-sheet though, because it was just messing things up.

**Comment by pstakoun** [comment]
I guess

```
[data-id] {
   font-weight: bolder;
}
```

could be added to the style at the top.

**Comment by marceloneil** [comment]
Ok

**Comment by marceloneil** [comment]
Maybe taking out the:

```
#messageContainer {
    width: 100%;
    height: 90%;
    word-wrap: break-word;
    overflow-y: scroll;
}
```

could affect the scrolling as well

**Comment by pstakoun** [comment]
If

```
    word-wrap: break-word;
    overflow-y: scroll;
```

is added to the corresponding element, it should be fine.

**Comment by marceloneil** [comment]
```
overflow-y: scroll;
```

Actually doesn't do anything really, it just adds a useless scrollbar on the side of the text, and looks ugly.

**Pull request merged**
